/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsUserPersonaScore
 */
public class ModelsUserPersonaScoreTest {
    private final ModelsUserPersonaScore model = new ModelsUserPersonaScore();

    /**
     * Model tests for ModelsUserPersonaScore
     */
    @Test
    public void testModelsUserPersonaScore() {
        // TODO: test ModelsUserPersonaScore
    }

    /**
     * Test the property 'personaId'
     */
    @Test
    public void personaIdTest() {
        // TODO: test personaId
    }

    /**
     * Test the property 'personaName'
     */
    @Test
    public void personaNameTest() {
        // TODO: test personaName
    }

    /**
     * Test the property 'personaScore'
     */
    @Test
    public void personaScoreTest() {
        // TODO: test personaScore
    }

}
