/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ModelsTagCategoricalAttributeFilter;
import com.konfigthis.client.model.ModelsUserMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsAutoMLRunUsersGetRequest
 */
public class ModelsAutoMLRunUsersGetRequestTest {
    private final ModelsAutoMLRunUsersGetRequest model = new ModelsAutoMLRunUsersGetRequest();

    /**
     * Model tests for ModelsAutoMLRunUsersGetRequest
     */
    @Test
    public void testModelsAutoMLRunUsersGetRequest() {
        // TODO: test ModelsAutoMLRunUsersGetRequest
    }

    /**
     * Test the property 'allowUsers'
     */
    @Test
    public void allowUsersTest() {
        // TODO: test allowUsers
    }

    /**
     * Test the property 'blockUsers'
     */
    @Test
    public void blockUsersTest() {
        // TODO: test blockUsers
    }

    /**
     * Test the property 'tagFilters'
     */
    @Test
    public void tagFiltersTest() {
        // TODO: test tagFilters
    }

}
