/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsCashflowWindowStatistics
 */
public class ModelsCashflowWindowStatisticsTest {
    private final ModelsCashflowWindowStatistics model = new ModelsCashflowWindowStatistics();

    /**
     * Model tests for ModelsCashflowWindowStatistics
     */
    @Test
    public void testModelsCashflowWindowStatistics() {
        // TODO: test ModelsCashflowWindowStatistics
    }

    /**
     * Test the property 'inflowAmount'
     */
    @Test
    public void inflowAmountTest() {
        // TODO: test inflowAmount
    }

    /**
     * Test the property 'outflowAmount'
     */
    @Test
    public void outflowAmountTest() {
        // TODO: test outflowAmount
    }

    /**
     * Test the property 'windowEnd'
     */
    @Test
    public void windowEndTest() {
        // TODO: test windowEnd
    }

    /**
     * Test the property 'windowStart'
     */
    @Test
    public void windowStartTest() {
        // TODO: test windowStart
    }

}
