/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ModelsAutoMLRunMetrics;
import com.konfigthis.client.model.ModelsInputLabelSummary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsAutoMLRunSummary
 */
public class ModelsAutoMLRunSummaryTest {
    private final ModelsAutoMLRunSummary model = new ModelsAutoMLRunSummary();

    /**
     * Model tests for ModelsAutoMLRunSummary
     */
    @Test
    public void testModelsAutoMLRunSummary() {
        // TODO: test ModelsAutoMLRunSummary
    }

    /**
     * Test the property 'engagementType'
     */
    @Test
    public void engagementTypeTest() {
        // TODO: test engagementType
    }

    /**
     * Test the property 'inputLabelSummary'
     */
    @Test
    public void inputLabelSummaryTest() {
        // TODO: test inputLabelSummary
    }

    /**
     * Test the property 'numberOfInferenceUsers'
     */
    @Test
    public void numberOfInferenceUsersTest() {
        // TODO: test numberOfInferenceUsers
    }

    /**
     * Test the property 'numberOfTrainUsers'
     */
    @Test
    public void numberOfTrainUsersTest() {
        // TODO: test numberOfTrainUsers
    }

    /**
     * Test the property 'runDescription'
     */
    @Test
    public void runDescriptionTest() {
        // TODO: test runDescription
    }

    /**
     * Test the property 'runId'
     */
    @Test
    public void runIdTest() {
        // TODO: test runId
    }

    /**
     * Test the property 'runMetrics'
     */
    @Test
    public void runMetricsTest() {
        // TODO: test runMetrics
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

}
