/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsUserTransactionsStatisticsResponse
 */
public class ModelsUserTransactionsStatisticsResponseTest {
    private final ModelsUserTransactionsStatisticsResponse model = new ModelsUserTransactionsStatisticsResponse();

    /**
     * Model tests for ModelsUserTransactionsStatisticsResponse
     */
    @Test
    public void testModelsUserTransactionsStatisticsResponse() {
        // TODO: test ModelsUserTransactionsStatisticsResponse
    }

    /**
     * Test the property 'averageTransactionValue'
     */
    @Test
    public void averageTransactionValueTest() {
        // TODO: test averageTransactionValue
    }

    /**
     * Test the property 'medianTransactionValue'
     */
    @Test
    public void medianTransactionValueTest() {
        // TODO: test medianTransactionValue
    }

    /**
     * Test the property 'transactionCount'
     */
    @Test
    public void transactionCountTest() {
        // TODO: test transactionCount
    }

}
