/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ModelsFacetWeightObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsPersonaCreateRequest
 */
public class ModelsPersonaCreateRequestTest {
    private final ModelsPersonaCreateRequest model = new ModelsPersonaCreateRequest();

    /**
     * Model tests for ModelsPersonaCreateRequest
     */
    @Test
    public void testModelsPersonaCreateRequest() {
        // TODO: test ModelsPersonaCreateRequest
    }

    /**
     * Test the property 'companyFacets'
     */
    @Test
    public void companyFacetsTest() {
        // TODO: test companyFacets
    }

    /**
     * Test the property 'demographicFacets'
     */
    @Test
    public void demographicFacetsTest() {
        // TODO: test demographicFacets
    }

    /**
     * Test the property 'interestFacets'
     */
    @Test
    public void interestFacetsTest() {
        // TODO: test interestFacets
    }

    /**
     * Test the property 'locations'
     */
    @Test
    public void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'personaName'
     */
    @Test
    public void personaNameTest() {
        // TODO: test personaName
    }

    /**
     * Test the property 'preDefinedPersonas'
     */
    @Test
    public void preDefinedPersonasTest() {
        // TODO: test preDefinedPersonas
    }

}
