/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsMerchantInfo
 */
public class ModelsMerchantInfoTest {
    private final ModelsMerchantInfo model = new ModelsMerchantInfo();

    /**
     * Model tests for ModelsMerchantInfo
     */
    @Test
    public void testModelsMerchantInfo() {
        // TODO: test ModelsMerchantInfo
    }

    /**
     * Test the property 'businessName'
     */
    @Test
    public void businessNameTest() {
        // TODO: test businessName
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'cnae'
     */
    @Test
    public void cnaeTest() {
        // TODO: test cnae
    }

    /**
     * Test the property 'cnpj'
     */
    @Test
    public void cnpjTest() {
        // TODO: test cnpj
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
