/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ModelsCategoricalAttributeFilter;
import com.konfigthis.client.model.ModelsNumericalAttributeFilter;
import com.konfigthis.client.model.ModelsTimestampAttributeFilter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsPostPersonaUsersRequest
 */
public class ModelsPostPersonaUsersRequestTest {
    private final ModelsPostPersonaUsersRequest model = new ModelsPostPersonaUsersRequest();

    /**
     * Model tests for ModelsPostPersonaUsersRequest
     */
    @Test
    public void testModelsPostPersonaUsersRequest() {
        // TODO: test ModelsPostPersonaUsersRequest
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'blocklist'
     */
    @Test
    public void blocklistTest() {
        // TODO: test blocklist
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'cboCode'
     */
    @Test
    public void cboCodeTest() {
        // TODO: test cboCode
    }

    /**
     * Test the property 'declaredMonthlyIncome'
     */
    @Test
    public void declaredMonthlyIncomeTest() {
        // TODO: test declaredMonthlyIncome
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

}
