/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsAccountCashflowOverview
 */
public class ModelsAccountCashflowOverviewTest {
    private final ModelsAccountCashflowOverview model = new ModelsAccountCashflowOverview();

    /**
     * Model tests for ModelsAccountCashflowOverview
     */
    @Test
    public void testModelsAccountCashflowOverview() {
        // TODO: test ModelsAccountCashflowOverview
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'inflowAmount'
     */
    @Test
    public void inflowAmountTest() {
        // TODO: test inflowAmount
    }

    /**
     * Test the property 'netCashflowAmount'
     */
    @Test
    public void netCashflowAmountTest() {
        // TODO: test netCashflowAmount
    }

    /**
     * Test the property 'outflowAmount'
     */
    @Test
    public void outflowAmountTest() {
        // TODO: test outflowAmount
    }

}
