/*
 * Hyperplane API Gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ModelsBatchUserPersonasRequest;
import com.konfigthis.client.model.ModelsUserPersonasResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
public class UsersApiTest {

    private static UsersApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new UsersApi(apiClient);
    }

    /**
     * Get all the facet attributes for a list of users.
     *
     * Returns all personas associated with a user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllFacetAttributesTest() throws ApiException {
        List<String> userIds = null;
        String moduleId = null;
        String month = null;
        Double personaScoreThreshold = null;
        List<ModelsUserPersonasResponse> response = api.getAllFacetAttributes(userIds)
                .moduleId(moduleId)
                .month(month)
                .personaScoreThreshold(personaScoreThreshold)
                .execute();
        // TODO: test validations
    }

    /**
     * List personas associated with a user.
     *
     * Returns a list of personas and their scores for a given user. Personas are sorted by their persona score, in descending order.  You can also specify the minimum persona score threshold that a user must meet to be included in the response. Defaults to hyperplane&#39;s suggested threshold to determine if the user belongs to the persona.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listUserPersonasTest() throws ApiException {
        String userId = null;
        String moduleId = null;
        String month = null;
        Double personaScoreThreshold = null;
        ModelsUserPersonasResponse response = api.listUserPersonas(userId)
                .moduleId(moduleId)
                .month(month)
                .personaScoreThreshold(personaScoreThreshold)
                .execute();
        // TODO: test validations
    }

}
